// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeoAuto.AuditService.Infrastructure.Database;

#nullable disable

namespace SeoAuto.AuditService.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.AuditRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditRequests");
                });

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.RawMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessibilityScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuditRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("BestPracticesScore")
                        .HasColumnType("integer");

                    b.Property<float>("CLS")
                        .HasColumnType("real");

                    b.Property<int>("FCP_ms")
                        .HasColumnType("integer");

                    b.Property<int>("INP_ms")
                        .HasColumnType("integer");

                    b.Property<int>("LCP_ms")
                        .HasColumnType("integer");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("integer");

                    b.Property<int>("SeoScore")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedIndex_ms")
                        .HasColumnType("integer");

                    b.Property<int>("TTFB_ms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditRequestId")
                        .IsUnique();

                    b.ToTable("RawMetrics");
                });

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.SeoAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("H1Count")
                        .HasColumnType("integer");

                    b.Property<bool>("HasRobotsTxt")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSitemap")
                        .HasColumnType("boolean");

                    b.Property<int>("ImagesWithoutAlt")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenGraphData")
                        .HasColumnType("jsonb");

                    b.Property<string>("StructuredData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuditRequestId")
                        .IsUnique();

                    b.ToTable("SeoAnalyses");
                });

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.RawMetrics", b =>
                {
                    b.HasOne("SeoAuto.AuditService.Domain.Entities.AuditRequest", "AuditRequest")
                        .WithOne("RawMetrics")
                        .HasForeignKey("SeoAuto.AuditService.Domain.Entities.RawMetrics", "AuditRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRequest");
                });

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.SeoAnalysis", b =>
                {
                    b.HasOne("SeoAuto.AuditService.Domain.Entities.AuditRequest", "AuditRequest")
                        .WithOne("SeoAnalysis")
                        .HasForeignKey("SeoAuto.AuditService.Domain.Entities.SeoAnalysis", "AuditRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRequest");
                });

            modelBuilder.Entity("SeoAuto.AuditService.Domain.Entities.AuditRequest", b =>
                {
                    b.Navigation("RawMetrics");

                    b.Navigation("SeoAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
