// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeoAuto.ReportService.Infrastructure.Database;

#nullable disable

namespace SeoAuto.ReportService.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260911115956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessibilityScore")
                        .HasColumnType("integer");

                    b.Property<string>("AiSuggestions")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("AuditRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("BestPracticesScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("PerformanceData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("integer");

                    b.Property<string>("SeoData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SeoScore")
                        .HasColumnType("integer");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WebsiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuditRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Website", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Report", b =>
                {
                    b.HasOne("SeoAuto.ReportService.Domain.Entities.Website", "Website")
                        .WithMany("Reports")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Website");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Website", b =>
                {
                    b.HasOne("SeoAuto.ReportService.Domain.Entities.Project", "Project")
                        .WithMany("Websites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Project", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("SeoAuto.ReportService.Domain.Entities.Website", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
